package com.zdzc.electrocar.entity;

import java.util.Date;

public class AlarmEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gps_alarm.id
     *
     * @mbg.generated Wed Aug 30 23:26:02 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gps_alarm.device_id
     *
     * @mbg.generated Wed Aug 30 23:26:02 CST 2017
     */
    private String deviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gps_alarm.alarm_status
     *
     * @mbg.generated Wed Aug 30 23:26:02 CST 2017
     */
    private String alarmStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gps_alarm.alarm_handle
     *
     * @mbg.generated Wed Aug 30 23:26:02 CST 2017
     */
    private Integer alarmHandle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gps_alarm.vehicle_status
     *
     * @mbg.generated Wed Aug 30 23:26:02 CST 2017
     */
    private String vehicleStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gps_alarm.longitude
     *
     * @mbg.generated Wed Aug 30 23:26:02 CST 2017
     */
    private Double longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gps_alarm.latitude
     *
     * @mbg.generated Wed Aug 30 23:26:02 CST 2017
     */
    private Double latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gps_alarm.height
     *
     * @mbg.generated Wed Aug 30 23:26:02 CST 2017
     */
    private Double height;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gps_alarm.speed
     *
     * @mbg.generated Wed Aug 30 23:26:02 CST 2017
     */
    private Double speed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gps_alarm.direction
     *
     * @mbg.generated Wed Aug 30 23:26:02 CST 2017
     */
    private Double direction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gps_alarm.time
     *
     * @mbg.generated Wed Aug 30 23:26:02 CST 2017
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gps_alarm.milestone
     *
     * @mbg.generated Wed Aug 30 23:26:02 CST 2017
     */
    private Double milestone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gps_alarm.oil
     *
     * @mbg.generated Wed Aug 30 23:26:02 CST 2017
     */
    private Double oil;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gps_alarm.speed2
     *
     * @mbg.generated Wed Aug 30 23:26:02 CST 2017
     */
    private Double speed2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gps_alarm.signal_status
     *
     * @mbg.generated Wed Aug 30 23:26:02 CST 2017
     */
    private String signalStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gps_alarm.io_status
     *
     * @mbg.generated Wed Aug 30 23:26:02 CST 2017
     */
    private String ioStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gps_alarm.analog
     *
     * @mbg.generated Wed Aug 30 23:26:02 CST 2017
     */
    private String analog;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gps_alarm.wiff
     *
     * @mbg.generated Wed Aug 30 23:26:02 CST 2017
     */
    private Integer wiff;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gps_alarm.satellite_num
     *
     * @mbg.generated Wed Aug 30 23:26:02 CST 2017
     */
    private Integer satelliteNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gps_alarm.create_time
     *
     * @mbg.generated Wed Aug 30 23:26:02 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gps_alarm.vendor
     *
     * @mbg.generated Wed Aug 30 23:26:02 CST 2017
     */
    private Integer vendor;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gps_alarm.id
     *
     * @return the value of t_gps_alarm.id
     *
     * @mbg.generated Wed Aug 30 23:26:02 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gps_alarm.id
     *
     * @param id the value for t_gps_alarm.id
     *
     * @mbg.generated Wed Aug 30 23:26:02 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gps_alarm.device_id
     *
     * @return the value of t_gps_alarm.device_id
     *
     * @mbg.generated Wed Aug 30 23:26:02 CST 2017
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gps_alarm.device_id
     *
     * @param deviceId the value for t_gps_alarm.device_id
     *
     * @mbg.generated Wed Aug 30 23:26:02 CST 2017
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId == null ? null : deviceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gps_alarm.alarm_status
     *
     * @return the value of t_gps_alarm.alarm_status
     *
     * @mbg.generated Wed Aug 30 23:26:02 CST 2017
     */
    public String getAlarmStatus() {
        return alarmStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gps_alarm.alarm_status
     *
     * @param alarmStatus the value for t_gps_alarm.alarm_status
     *
     * @mbg.generated Wed Aug 30 23:26:02 CST 2017
     */
    public void setAlarmStatus(String alarmStatus) {
        this.alarmStatus = alarmStatus == null ? null : alarmStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gps_alarm.alarm_handle
     *
     * @return the value of t_gps_alarm.alarm_handle
     *
     * @mbg.generated Wed Aug 30 23:26:02 CST 2017
     */
    public Integer getAlarmHandle() {
        return alarmHandle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gps_alarm.alarm_handle
     *
     * @param alarmHandle the value for t_gps_alarm.alarm_handle
     *
     * @mbg.generated Wed Aug 30 23:26:02 CST 2017
     */
    public void setAlarmHandle(Integer alarmHandle) {
        this.alarmHandle = alarmHandle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gps_alarm.vehicle_status
     *
     * @return the value of t_gps_alarm.vehicle_status
     *
     * @mbg.generated Wed Aug 30 23:26:02 CST 2017
     */
    public String getVehicleStatus() {
        return vehicleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gps_alarm.vehicle_status
     *
     * @param vehicleStatus the value for t_gps_alarm.vehicle_status
     *
     * @mbg.generated Wed Aug 30 23:26:02 CST 2017
     */
    public void setVehicleStatus(String vehicleStatus) {
        this.vehicleStatus = vehicleStatus == null ? null : vehicleStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gps_alarm.longitude
     *
     * @return the value of t_gps_alarm.longitude
     *
     * @mbg.generated Wed Aug 30 23:26:02 CST 2017
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gps_alarm.longitude
     *
     * @param longitude the value for t_gps_alarm.longitude
     *
     * @mbg.generated Wed Aug 30 23:26:02 CST 2017
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gps_alarm.latitude
     *
     * @return the value of t_gps_alarm.latitude
     *
     * @mbg.generated Wed Aug 30 23:26:02 CST 2017
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gps_alarm.latitude
     *
     * @param latitude the value for t_gps_alarm.latitude
     *
     * @mbg.generated Wed Aug 30 23:26:02 CST 2017
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gps_alarm.height
     *
     * @return the value of t_gps_alarm.height
     *
     * @mbg.generated Wed Aug 30 23:26:02 CST 2017
     */
    public Double getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gps_alarm.height
     *
     * @param height the value for t_gps_alarm.height
     *
     * @mbg.generated Wed Aug 30 23:26:02 CST 2017
     */
    public void setHeight(Double height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gps_alarm.speed
     *
     * @return the value of t_gps_alarm.speed
     *
     * @mbg.generated Wed Aug 30 23:26:02 CST 2017
     */
    public Double getSpeed() {
        return speed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gps_alarm.speed
     *
     * @param speed the value for t_gps_alarm.speed
     *
     * @mbg.generated Wed Aug 30 23:26:02 CST 2017
     */
    public void setSpeed(Double speed) {
        this.speed = speed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gps_alarm.direction
     *
     * @return the value of t_gps_alarm.direction
     *
     * @mbg.generated Wed Aug 30 23:26:02 CST 2017
     */
    public Double getDirection() {
        return direction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gps_alarm.direction
     *
     * @param direction the value for t_gps_alarm.direction
     *
     * @mbg.generated Wed Aug 30 23:26:02 CST 2017
     */
    public void setDirection(Double direction) {
        this.direction = direction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gps_alarm.time
     *
     * @return the value of t_gps_alarm.time
     *
     * @mbg.generated Wed Aug 30 23:26:02 CST 2017
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gps_alarm.time
     *
     * @param time the value for t_gps_alarm.time
     *
     * @mbg.generated Wed Aug 30 23:26:02 CST 2017
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gps_alarm.milestone
     *
     * @return the value of t_gps_alarm.milestone
     *
     * @mbg.generated Wed Aug 30 23:26:02 CST 2017
     */
    public Double getMilestone() {
        return milestone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gps_alarm.milestone
     *
     * @param milestone the value for t_gps_alarm.milestone
     *
     * @mbg.generated Wed Aug 30 23:26:02 CST 2017
     */
    public void setMilestone(Double milestone) {
        this.milestone = milestone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gps_alarm.oil
     *
     * @return the value of t_gps_alarm.oil
     *
     * @mbg.generated Wed Aug 30 23:26:02 CST 2017
     */
    public Double getOil() {
        return oil;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gps_alarm.oil
     *
     * @param oil the value for t_gps_alarm.oil
     *
     * @mbg.generated Wed Aug 30 23:26:02 CST 2017
     */
    public void setOil(Double oil) {
        this.oil = oil;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gps_alarm.speed2
     *
     * @return the value of t_gps_alarm.speed2
     *
     * @mbg.generated Wed Aug 30 23:26:02 CST 2017
     */
    public Double getSpeed2() {
        return speed2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gps_alarm.speed2
     *
     * @param speed2 the value for t_gps_alarm.speed2
     *
     * @mbg.generated Wed Aug 30 23:26:02 CST 2017
     */
    public void setSpeed2(Double speed2) {
        this.speed2 = speed2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gps_alarm.signal_status
     *
     * @return the value of t_gps_alarm.signal_status
     *
     * @mbg.generated Wed Aug 30 23:26:02 CST 2017
     */
    public String getSignalStatus() {
        return signalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gps_alarm.signal_status
     *
     * @param signalStatus the value for t_gps_alarm.signal_status
     *
     * @mbg.generated Wed Aug 30 23:26:02 CST 2017
     */
    public void setSignalStatus(String signalStatus) {
        this.signalStatus = signalStatus == null ? null : signalStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gps_alarm.io_status
     *
     * @return the value of t_gps_alarm.io_status
     *
     * @mbg.generated Wed Aug 30 23:26:02 CST 2017
     */
    public String getIoStatus() {
        return ioStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gps_alarm.io_status
     *
     * @param ioStatus the value for t_gps_alarm.io_status
     *
     * @mbg.generated Wed Aug 30 23:26:02 CST 2017
     */
    public void setIoStatus(String ioStatus) {
        this.ioStatus = ioStatus == null ? null : ioStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gps_alarm.analog
     *
     * @return the value of t_gps_alarm.analog
     *
     * @mbg.generated Wed Aug 30 23:26:02 CST 2017
     */
    public String getAnalog() {
        return analog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gps_alarm.analog
     *
     * @param analog the value for t_gps_alarm.analog
     *
     * @mbg.generated Wed Aug 30 23:26:02 CST 2017
     */
    public void setAnalog(String analog) {
        this.analog = analog == null ? null : analog.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gps_alarm.wiff
     *
     * @return the value of t_gps_alarm.wiff
     *
     * @mbg.generated Wed Aug 30 23:26:02 CST 2017
     */
    public Integer getWiff() {
        return wiff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gps_alarm.wiff
     *
     * @param wiff the value for t_gps_alarm.wiff
     *
     * @mbg.generated Wed Aug 30 23:26:02 CST 2017
     */
    public void setWiff(Integer wiff) {
        this.wiff = wiff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gps_alarm.satellite_num
     *
     * @return the value of t_gps_alarm.satellite_num
     *
     * @mbg.generated Wed Aug 30 23:26:02 CST 2017
     */
    public Integer getSatelliteNum() {
        return satelliteNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gps_alarm.satellite_num
     *
     * @param satelliteNum the value for t_gps_alarm.satellite_num
     *
     * @mbg.generated Wed Aug 30 23:26:02 CST 2017
     */
    public void setSatelliteNum(Integer satelliteNum) {
        this.satelliteNum = satelliteNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gps_alarm.create_time
     *
     * @return the value of t_gps_alarm.create_time
     *
     * @mbg.generated Wed Aug 30 23:26:02 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gps_alarm.create_time
     *
     * @param createTime the value for t_gps_alarm.create_time
     *
     * @mbg.generated Wed Aug 30 23:26:02 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gps_alarm.vendor
     *
     * @return the value of t_gps_alarm.vendor
     *
     * @mbg.generated Wed Aug 30 23:26:02 CST 2017
     */
    public Integer getVendor() {
        return vendor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gps_alarm.vendor
     *
     * @param vendor the value for t_gps_alarm.vendor
     *
     * @mbg.generated Wed Aug 30 23:26:02 CST 2017
     */
    public void setVendor(Integer vendor) {
        this.vendor = vendor;
    }
}