package com.zdzc.electrocar.entity;

import java.util.Date;

public class GPSEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gps.id
     *
     * @mbggenerated Thu Aug 31 21:23:17 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gps.device_id
     *
     * @mbggenerated Thu Aug 31 21:23:17 CST 2017
     */
    private String deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gps.alarm_status
     *
     * @mbggenerated Thu Aug 31 21:23:17 CST 2017
     */
    private Integer alarmStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gps.vehicle_status
     *
     * @mbggenerated Thu Aug 31 21:23:17 CST 2017
     */
    private Integer vehicleStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gps.longitude
     *
     * @mbggenerated Thu Aug 31 21:23:17 CST 2017
     */
    private Double longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gps.latitude
     *
     * @mbggenerated Thu Aug 31 21:23:17 CST 2017
     */
    private Double latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gps.height
     *
     * @mbggenerated Thu Aug 31 21:23:17 CST 2017
     */
    private Double height;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gps.speed
     *
     * @mbggenerated Thu Aug 31 21:23:17 CST 2017
     */
    private Double speed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gps.direction
     *
     * @mbggenerated Thu Aug 31 21:23:17 CST 2017
     */
    private Double direction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gps.time
     *
     * @mbggenerated Thu Aug 31 21:23:17 CST 2017
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gps.milestone
     *
     * @mbggenerated Thu Aug 31 21:23:17 CST 2017
     */
    private Double milestone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gps.oil
     *
     * @mbggenerated Thu Aug 31 21:23:17 CST 2017
     */
    private Double oil;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gps.speed2
     *
     * @mbggenerated Thu Aug 31 21:23:17 CST 2017
     */
    private Double speed2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gps.signal_status
     *
     * @mbggenerated Thu Aug 31 21:23:17 CST 2017
     */
    private Integer signalStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gps.io_status
     *
     * @mbggenerated Thu Aug 31 21:23:17 CST 2017
     */
    private Integer ioStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gps.analog
     *
     * @mbggenerated Thu Aug 31 21:23:17 CST 2017
     */
    private String analog;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gps.wiff
     *
     * @mbggenerated Thu Aug 31 21:23:17 CST 2017
     */
    private Integer wiff;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gps.satellite_num
     *
     * @mbggenerated Thu Aug 31 21:23:17 CST 2017
     */
    private Integer satelliteNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gps.create_time
     *
     * @mbggenerated Thu Aug 31 21:23:17 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gps.vendor
     *
     * @mbggenerated Thu Aug 31 21:23:17 CST 2017
     */
    private Integer vendor;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gps.id
     *
     * @return the value of t_gps.id
     *
     * @mbggenerated Thu Aug 31 21:23:17 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gps.id
     *
     * @param id the value for t_gps.id
     *
     * @mbggenerated Thu Aug 31 21:23:17 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gps.device_id
     *
     * @return the value of t_gps.device_id
     *
     * @mbggenerated Thu Aug 31 21:23:17 CST 2017
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gps.device_id
     *
     * @param deviceId the value for t_gps.device_id
     *
     * @mbggenerated Thu Aug 31 21:23:17 CST 2017
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId == null ? null : deviceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gps.alarm_status
     *
     * @return the value of t_gps.alarm_status
     *
     * @mbggenerated Thu Aug 31 21:23:17 CST 2017
     */
    public Integer getAlarmStatus() {
        return alarmStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gps.alarm_status
     *
     * @param alarmStatus the value for t_gps.alarm_status
     *
     * @mbggenerated Thu Aug 31 21:23:17 CST 2017
     */
    public void setAlarmStatus(Integer alarmStatus) {
        this.alarmStatus = alarmStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gps.vehicle_status
     *
     * @return the value of t_gps.vehicle_status
     *
     * @mbggenerated Thu Aug 31 21:23:17 CST 2017
     */
    public Integer getVehicleStatus() {
        return vehicleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gps.vehicle_status
     *
     * @param vehicleStatus the value for t_gps.vehicle_status
     *
     * @mbggenerated Thu Aug 31 21:23:17 CST 2017
     */
    public void setVehicleStatus(Integer vehicleStatus) {
        this.vehicleStatus = vehicleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gps.longitude
     *
     * @return the value of t_gps.longitude
     *
     * @mbggenerated Thu Aug 31 21:23:17 CST 2017
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gps.longitude
     *
     * @param longitude the value for t_gps.longitude
     *
     * @mbggenerated Thu Aug 31 21:23:17 CST 2017
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gps.latitude
     *
     * @return the value of t_gps.latitude
     *
     * @mbggenerated Thu Aug 31 21:23:17 CST 2017
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gps.latitude
     *
     * @param latitude the value for t_gps.latitude
     *
     * @mbggenerated Thu Aug 31 21:23:17 CST 2017
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gps.height
     *
     * @return the value of t_gps.height
     *
     * @mbggenerated Thu Aug 31 21:23:17 CST 2017
     */
    public Double getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gps.height
     *
     * @param height the value for t_gps.height
     *
     * @mbggenerated Thu Aug 31 21:23:17 CST 2017
     */
    public void setHeight(Double height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gps.speed
     *
     * @return the value of t_gps.speed
     *
     * @mbggenerated Thu Aug 31 21:23:17 CST 2017
     */
    public Double getSpeed() {
        return speed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gps.speed
     *
     * @param speed the value for t_gps.speed
     *
     * @mbggenerated Thu Aug 31 21:23:17 CST 2017
     */
    public void setSpeed(Double speed) {
        this.speed = speed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gps.direction
     *
     * @return the value of t_gps.direction
     *
     * @mbggenerated Thu Aug 31 21:23:17 CST 2017
     */
    public Double getDirection() {
        return direction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gps.direction
     *
     * @param direction the value for t_gps.direction
     *
     * @mbggenerated Thu Aug 31 21:23:17 CST 2017
     */
    public void setDirection(Double direction) {
        this.direction = direction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gps.time
     *
     * @return the value of t_gps.time
     *
     * @mbggenerated Thu Aug 31 21:23:17 CST 2017
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gps.time
     *
     * @param time the value for t_gps.time
     *
     * @mbggenerated Thu Aug 31 21:23:17 CST 2017
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gps.milestone
     *
     * @return the value of t_gps.milestone
     *
     * @mbggenerated Thu Aug 31 21:23:17 CST 2017
     */
    public Double getMilestone() {
        return milestone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gps.milestone
     *
     * @param milestone the value for t_gps.milestone
     *
     * @mbggenerated Thu Aug 31 21:23:17 CST 2017
     */
    public void setMilestone(Double milestone) {
        this.milestone = milestone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gps.oil
     *
     * @return the value of t_gps.oil
     *
     * @mbggenerated Thu Aug 31 21:23:17 CST 2017
     */
    public Double getOil() {
        return oil;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gps.oil
     *
     * @param oil the value for t_gps.oil
     *
     * @mbggenerated Thu Aug 31 21:23:17 CST 2017
     */
    public void setOil(Double oil) {
        this.oil = oil;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gps.speed2
     *
     * @return the value of t_gps.speed2
     *
     * @mbggenerated Thu Aug 31 21:23:17 CST 2017
     */
    public Double getSpeed2() {
        return speed2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gps.speed2
     *
     * @param speed2 the value for t_gps.speed2
     *
     * @mbggenerated Thu Aug 31 21:23:17 CST 2017
     */
    public void setSpeed2(Double speed2) {
        this.speed2 = speed2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gps.signal_status
     *
     * @return the value of t_gps.signal_status
     *
     * @mbggenerated Thu Aug 31 21:23:17 CST 2017
     */
    public Integer getSignalStatus() {
        return signalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gps.signal_status
     *
     * @param signalStatus the value for t_gps.signal_status
     *
     * @mbggenerated Thu Aug 31 21:23:17 CST 2017
     */
    public void setSignalStatus(Integer signalStatus) {
        this.signalStatus = signalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gps.io_status
     *
     * @return the value of t_gps.io_status
     *
     * @mbggenerated Thu Aug 31 21:23:17 CST 2017
     */
    public Integer getIoStatus() {
        return ioStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gps.io_status
     *
     * @param ioStatus the value for t_gps.io_status
     *
     * @mbggenerated Thu Aug 31 21:23:17 CST 2017
     */
    public void setIoStatus(Integer ioStatus) {
        this.ioStatus = ioStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gps.analog
     *
     * @return the value of t_gps.analog
     *
     * @mbggenerated Thu Aug 31 21:23:17 CST 2017
     */
    public String getAnalog() {
        return analog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gps.analog
     *
     * @param analog the value for t_gps.analog
     *
     * @mbggenerated Thu Aug 31 21:23:17 CST 2017
     */
    public void setAnalog(String analog) {
        this.analog = analog == null ? null : analog.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gps.wiff
     *
     * @return the value of t_gps.wiff
     *
     * @mbggenerated Thu Aug 31 21:23:17 CST 2017
     */
    public Integer getWiff() {
        return wiff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gps.wiff
     *
     * @param wiff the value for t_gps.wiff
     *
     * @mbggenerated Thu Aug 31 21:23:17 CST 2017
     */
    public void setWiff(Integer wiff) {
        this.wiff = wiff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gps.satellite_num
     *
     * @return the value of t_gps.satellite_num
     *
     * @mbggenerated Thu Aug 31 21:23:17 CST 2017
     */
    public Integer getSatelliteNum() {
        return satelliteNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gps.satellite_num
     *
     * @param satelliteNum the value for t_gps.satellite_num
     *
     * @mbggenerated Thu Aug 31 21:23:17 CST 2017
     */
    public void setSatelliteNum(Integer satelliteNum) {
        this.satelliteNum = satelliteNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gps.create_time
     *
     * @return the value of t_gps.create_time
     *
     * @mbggenerated Thu Aug 31 21:23:17 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gps.create_time
     *
     * @param createTime the value for t_gps.create_time
     *
     * @mbggenerated Thu Aug 31 21:23:17 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gps.vendor
     *
     * @return the value of t_gps.vendor
     *
     * @mbggenerated Thu Aug 31 21:23:17 CST 2017
     */
    public Integer getVendor() {
        return vendor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gps.vendor
     *
     * @param vendor the value for t_gps.vendor
     *
     * @mbggenerated Thu Aug 31 21:23:17 CST 2017
     */
    public void setVendor(Integer vendor) {
        this.vendor = vendor;
    }
}