package com.zdzc.electrocar.mapper;

import com.zdzc.electrocar.entity.AlarmEntity;
import java.util.List;

public interface AlarmEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gps_alarm
     *
     * @mbg.generated Wed Aug 30 23:26:02 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gps_alarm
     *
     * @mbg.generated Wed Aug 30 23:26:02 CST 2017
     */
    int insert(AlarmEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gps_alarm
     *
     * @mbg.generated Wed Aug 30 23:26:02 CST 2017
     */
    AlarmEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gps_alarm
     *
     * @mbg.generated Wed Aug 30 23:26:02 CST 2017
     */
    List<AlarmEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gps_alarm
     *
     * @mbg.generated Wed Aug 30 23:26:02 CST 2017
     */
    int updateByPrimaryKey(AlarmEntity record);
}